// Shark.swift
// Generated by Shark https://github.com/kaandedeoglu/Shark

import SwiftUI

// swiftlint:disable all
// swiftformat:disable all
private let bundle: Bundle = {
    class Custom {}
    return Bundle(for: Custom.self)
}()

extension String {
    public var localizedStringKey: LocalizedStringKey { .init(self) }
}

public enum R {
    public enum I: CaseIterable {
    }

    public enum C: CaseIterable {
    }

    public enum L {
        /// USB Devices
        public static var App_DEVICES_WINDOW: String { return NSLocalizedString("App_DEVICES_WINDOW", bundle: bundle, comment: "") }

        /// LSUSD
        public static var App_NAME: String { return NSLocalizedString("App_NAME", bundle: bundle, comment: "") }

        /// Serial device
        public static var Badge_SERIAL_DEVICE: String { return NSLocalizedString("Badge_SERIAL_DEVICE", bundle: bundle, comment: "") }

        /// Clear
        public static var Common_CLEAR: String { return NSLocalizedString("Common_CLEAR", bundle: bundle, comment: "") }

        /// Copy
        public static var Common_COPY: String { return NSLocalizedString("Common_COPY", bundle: bundle, comment: "") }

        /// Export
        public static var Common_EXPORT: String { return NSLocalizedString("Common_EXPORT", bundle: bundle, comment: "") }

        /// Show All Devices…
        public static var Common_OPEN_WINDOW: String { return NSLocalizedString("Common_OPEN_WINDOW", bundle: bundle, comment: "") }

        /// Quit LSUSD
        public static var Common_QUIT: String { return NSLocalizedString("Common_QUIT", bundle: bundle, comment: "") }

        /// Refresh
        public static var Common_REFRESH: String { return NSLocalizedString("Common_REFRESH", bundle: bundle, comment: "") }

        /// Settings…
        public static var Common_SETTINGS: String { return NSLocalizedString("Common_SETTINGS", bundle: bundle, comment: "") }

        /// Show USB hubs
        public static var Common_SHOW_HUBS: String { return NSLocalizedString("Common_SHOW_HUBS", bundle: bundle, comment: "") }

        /// Address
        public static var Details_ADDRESS: String { return NSLocalizedString("Details_ADDRESS", bundle: bundle, comment: "") }

        /// Bus
        public static var Details_BUS: String { return NSLocalizedString("Details_BUS", bundle: bundle, comment: "") }

        /// Connection
        public static var Details_CONNECTION: String { return NSLocalizedString("Details_CONNECTION", bundle: bundle, comment: "") }

        /// Device node
        public static var Details_DEVICE_NODE: String { return NSLocalizedString("Details_DEVICE_NODE", bundle: bundle, comment: "") }

        /// USB hub
        public static var Details_HUB: String { return NSLocalizedString("Details_HUB", bundle: bundle, comment: "") }

        /// Identity
        public static var Details_IDENTITY: String { return NSLocalizedString("Details_IDENTITY", bundle: bundle, comment: "") }

        /// Location ID
        public static var Details_LOCATION: String { return NSLocalizedString("Details_LOCATION", bundle: bundle, comment: "") }

        /// No
        public static var Details_NO: String { return NSLocalizedString("Details_NO", bundle: bundle, comment: "") }

        /// Product
        public static var Details_PRODUCT: String { return NSLocalizedString("Details_PRODUCT", bundle: bundle, comment: "") }

        /// Product ID
        public static var Details_PRODUCT_ID: String { return NSLocalizedString("Details_PRODUCT_ID", bundle: bundle, comment: "") }

        /// Device release
        public static var Details_RELEASE: String { return NSLocalizedString("Details_RELEASE", bundle: bundle, comment: "") }

        /// Serial number
        public static var Details_SERIAL: String { return NSLocalizedString("Details_SERIAL", bundle: bundle, comment: "") }

        /// Link speed
        public static var Details_SPEED: String { return NSLocalizedString("Details_SPEED", bundle: bundle, comment: "") }

        /// Device Details
        public static var Details_TITLE: String { return NSLocalizedString("Details_TITLE", bundle: bundle, comment: "") }

        /// Vendor
        public static var Details_VENDOR: String { return NSLocalizedString("Details_VENDOR", bundle: bundle, comment: "") }

        /// Vendor ID
        public static var Details_VENDOR_ID: String { return NSLocalizedString("Details_VENDOR_ID", bundle: bundle, comment: "") }

        /// Yes
        public static var Details_YES: String { return NSLocalizedString("Details_YES", bundle: bundle, comment: "") }

        /// Dismiss
        public static var Error_DISMISS: String { return NSLocalizedString("Error_DISMISS", bundle: bundle, comment: "") }

        /// USB data could not be read
        public static var Error_TITLE: String { return NSLocalizedString("Error_TITLE", bundle: bundle, comment: "") }

        /// Connected
        public static var Event_ADD: String { return NSLocalizedString("Event_ADD", bundle: bundle, comment: "") }

        /// Present
        public static var Event_PRESENT: String { return NSLocalizedString("Event_PRESENT", bundle: bundle, comment: "") }

        /// Disconnected
        public static var Event_REMOVE: String { return NSLocalizedString("Event_REMOVE", bundle: bundle, comment: "") }

        /// Copy as CSV
        public static var Export_COPY_CSV: String { return NSLocalizedString("Export_COPY_CSV", bundle: bundle, comment: "") }

        /// Copy as JSON
        public static var Export_COPY_JSON: String { return NSLocalizedString("Export_COPY_JSON", bundle: bundle, comment: "") }

        /// Copy as tab-separated text
        public static var Export_COPY_TSV: String { return NSLocalizedString("Export_COPY_TSV", bundle: bundle, comment: "") }

        /// Export CSV…
        public static var Export_CSV: String { return NSLocalizedString("Export_CSV", bundle: bundle, comment: "") }

        /// Export JSON…
        public static var Export_JSON: String { return NSLocalizedString("Export_JSON", bundle: bundle, comment: "") }

        /// Export tab-separated text…
        public static var Export_TSV: String { return NSLocalizedString("Export_TSV", bundle: bundle, comment: "") }

        /// LSUSD, %@, %@
        public static func MenuBar_COUNT_ACCESSIBILITY(_ value1: String,_ value2: String) -> String {
            return String(format: NSLocalizedString("MenuBar_COUNT_ACCESSIBILITY", bundle: bundle, comment: ""), value1, value2)
        }

        /// Search USB devices
        public static var Search_PROMPT: String { return NSLocalizedString("Search_PROMPT", bundle: bundle, comment: "") }

        /// LSUSD follows the macOS appearance and uses the system typeface.
        public static var Settings_APPEARANCE_NOTE: String { return NSLocalizedString("Settings_APPEARANCE_NOTE", bundle: bundle, comment: "") }

        /// General
        public static var Settings_GENERAL: String { return NSLocalizedString("Settings_GENERAL", bundle: bundle, comment: "") }

        /// Hubs are hidden by default to keep the device list focused.
        public static var Settings_HUBS_NOTE: String { return NSLocalizedString("Settings_HUBS_NOTE", bundle: bundle, comment: "") }

        /// Alphabetically
        public static var Settings_SORT_ALPHABETICAL: String { return NSLocalizedString("Settings_SORT_ALPHABETICAL", bundle: bundle, comment: "") }

        /// Sort devices by
        public static var Settings_SORT_BY: String { return NSLocalizedString("Settings_SORT_BY", bundle: bundle, comment: "") }

        /// USB device type
        public static var Settings_SORT_DEVICE_TYPE: String { return NSLocalizedString("Settings_SORT_DEVICE_TYPE", bundle: bundle, comment: "") }

        /// Speed
        public static var Settings_SORT_SPEED: String { return NSLocalizedString("Settings_SORT_SPEED", bundle: bundle, comment: "") }

        /// Devices
        public static var Sidebar_DEVICES: String { return NSLocalizedString("Sidebar_DEVICES", bundle: bundle, comment: "") }

        /// Events
        public static var Sidebar_EVENTS: String { return NSLocalizedString("Sidebar_EVENTS", bundle: bundle, comment: "") }

        /// Serial
        public static var Sidebar_SERIAL: String { return NSLocalizedString("Sidebar_SERIAL", bundle: bundle, comment: "") }

        /// Topology
        public static var Sidebar_TOPOLOGY: String { return NSLocalizedString("Sidebar_TOPOLOGY", bundle: bundle, comment: "") }

        /// %d USB devices
        public static func Status_DEVICE_COUNT(_ value1: Int) -> String {
            return String(format: NSLocalizedString("Status_DEVICE_COUNT", bundle: bundle, comment: ""), value1)
        }

        /// 1 USB device
        public static var Status_DEVICE_COUNT_ONE: String { return NSLocalizedString("Status_DEVICE_COUNT_ONE", bundle: bundle, comment: "") }

        /// Updated %@
        public static func Status_LAST_UPDATED(_ value1: String) -> String {
            return String(format: NSLocalizedString("Status_LAST_UPDATED", bundle: bundle, comment: ""), value1)
        }

        /// Reading USB devices…
        public static var Status_LOADING: String { return NSLocalizedString("Status_LOADING", bundle: bundle, comment: "") }

        /// No USB devices
        public static var Status_NO_DEVICES: String { return NSLocalizedString("Status_NO_DEVICES", bundle: bundle, comment: "") }

        /// Connect a USB device or refresh the list.
        public static var Status_NO_DEVICES_DESCRIPTION: String { return NSLocalizedString("Status_NO_DEVICES_DESCRIPTION", bundle: bundle, comment: "") }

        /// No connection events
        public static var Status_NO_EVENTS: String { return NSLocalizedString("Status_NO_EVENTS", bundle: bundle, comment: "") }

        /// USB serial connection changes appear here.
        public static var Status_NO_EVENTS_DESCRIPTION: String { return NSLocalizedString("Status_NO_EVENTS_DESCRIPTION", bundle: bundle, comment: "") }

        /// No USB serial devices
        public static var Status_NO_SERIAL: String { return NSLocalizedString("Status_NO_SERIAL", bundle: bundle, comment: "") }

        /// Compatible serial devices appear here automatically.
        public static var Status_NO_SERIAL_DESCRIPTION: String { return NSLocalizedString("Status_NO_SERIAL_DESCRIPTION", bundle: bundle, comment: "") }

        /// %d serial devices
        public static func Status_SERIAL_COUNT(_ value1: Int) -> String {
            return String(format: NSLocalizedString("Status_SERIAL_COUNT", bundle: bundle, comment: ""), value1)
        }

        /// 1 serial device
        public static var Status_SERIAL_COUNT_ONE: String { return NSLocalizedString("Status_SERIAL_COUNT_ONE", bundle: bundle, comment: "") }

        /// Bus
        public static var Table_BUS: String { return NSLocalizedString("Table_BUS", bundle: bundle, comment: "") }

        /// Device
        public static var Table_DEVICE: String { return NSLocalizedString("Table_DEVICE", bundle: bundle, comment: "") }

        /// Location ID
        public static var Table_LOCATION: String { return NSLocalizedString("Table_LOCATION", bundle: bundle, comment: "") }

        /// USB Product
        public static var Table_PRODUCT: String { return NSLocalizedString("Table_PRODUCT", bundle: bundle, comment: "") }

        /// Release
        public static var Table_RELEASE: String { return NSLocalizedString("Table_RELEASE", bundle: bundle, comment: "") }

        /// USB Serial
        public static var Table_SERIAL: String { return NSLocalizedString("Table_SERIAL", bundle: bundle, comment: "") }

        /// Speed
        public static var Table_SPEED: String { return NSLocalizedString("Table_SPEED", bundle: bundle, comment: "") }

        /// USB Vendor
        public static var Table_VENDOR: String { return NSLocalizedString("Table_VENDOR", bundle: bundle, comment: "") }

        /// VID:PID
        public static var Table_VIDPID: String { return NSLocalizedString("Table_VIDPID", bundle: bundle, comment: "") }
    }

    public enum D: CaseIterable {
    }
}
